FROM node:latest
WORKDIR /root/app
COPY . /root/app
WORKDIR /root/app
# RUN npm i --registry=https://registry.npm.taobao.org
ENV NODE_ENV=dev
# RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone
EXPOSE 7001