version: '3'
services: 
    nginx:
        image: nginx:latest
        ports: 
            - 8000:80
        restart: always
        volumes: 
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
        environment:
            TZ: Asia/Shanghai

    redis-server:
        image: redis:latest
        ports: 
            - 6479:6379
        restart: always
        environment:
            TZ: Asia/Shanghai

    mysql:
        image: mysql:latest
        ports: 
            - 3336:3306
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            TZ: Asia/Shanghai
        volumes: 
            - ./docker/init:/docker-entrypoint-initdb.d
            
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes: 
            - .:/root/app
        restart: always
        working_dir: /root/app
        ports: 
            - 8090:7001
        command: npm run dev
        environment: 
            TZ: Asia/Shanghai
        depends_on: 
            - redis-server
            - mysql
        links: 
            - mysql
            - redis-server:rs